0.0.0.0:80 {
  gzip
  header {
    Content-Security-Policy "frame-ancestors 'self';"
    X-Frame-Options "SAMEORIGIN"
    X-Content-Type-Options "nosniff"
    X-XSS-Protection "1; mode=block"
  }
  root /usr/share/nginx/html

  rewrite {
    r .*
    to {path} /
  }
}
